mg-chao/snow-shot

- src/app/draw/components/ocrBlocks/index.tsx
> fix: 修复部分情况下 OCR 结果文字过小的问题

- src-tauri/capabilities/default.json
- src/app/draw/components/drawCacheLayer/index.tsx
- src/app/tools/chat/page.tsx
- src/utils/appStore.ts
1. 修复固定截图后不保存绘画状态
2. 优化 Chat 的复制效果
> fix: 修复固定截图后不保存绘画状态和优化 Chat 的复制效果

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/ocr.rs
- src/app/draw/actions.ts
- src/app/draw/components/colorPicker/index.tsx
- src/utils/window.ts
> fix: 修复窗口闪烁和 OCR 某些情况下的识别丢失

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/lib.rs
- src-tauri/src/os/ui_automation/windows.rs
- src-tauri/src/os/utils/windows.rs
- src-tauri/src/screenshot.rs
- src/app/draw/actions.ts
- src/app/draw/components/selectLayer/index.tsx
- src/app/draw/page.tsx
- src/commands/screenshot.ts
> fix: 优化固定到屏幕的闪烁问题

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/capabilities/default.json
- src/app/draw/page.tsx
- src/app/globals.css
> fix: 修复显示器缩放比例获取错误

- package.json
- src-tauri/.gitignore
- src-tauri/src/scroll_screenshot.rs
- src-tauri/src/services/scroll_screenshot_service.rs
- src/app/contextWrap.tsx
- src/app/draw/components/drawToolbar/components/tools/scrollScreenshotTool/index.tsx
- src/app/draw/components/drawToolbar/index.tsx
- src/app/settings/systemSettings/page.tsx
- src/commands/scrollScreenshot.ts
- src/messages/zhHans/draw.ts
> perf: 滚动截图优化

- src-tauri/src/scroll_screenshot.rs
- src-tauri/src/services/scroll_screenshot_service.rs
- src/app/contextWrap.tsx
- src/app/draw/components/drawToolbar/components/tools/scrollScreenshotTool/index.tsx
- src/app/settings/systemSettings/page.tsx
> perf: 更好的滚动截图

- src-tauri/src/lib.rs
- src-tauri/src/scroll_screenshot.rs
- src-tauri/src/services/scroll_screenshot_service.rs
- src/app/draw/components/drawToolbar/components/tools/scrollScreenshotTool/index.tsx
- src/app/draw/page.tsx
- src/commands/scrollScreenshot.ts
> fix: 降低内存消耗

- package.json
- pnpm-lock.yaml
- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/capabilities/default.json
- src-tauri/src/lib.rs
- src-tauri/src/services/scroll_screenshot_service.rs
- src-tauri/tauri.conf.json
- src/app/components/globalEventHandler.tsx
- src/app/contextWrap.tsx
- src/app/draw/actions.ts
- src/app/draw/components/colorPicker/index.tsx
- src/app/draw/components/drawCacheLayer/excalidrawRenders/radioSelection.tsx
- src/app/draw/components/drawCacheLayer/index.tsx
- src/app/draw/components/drawToolbar/components/keyEventWrap/extra.ts
- src/app/draw/components/drawToolbar/components/tools/blurTool.tsx
- src/app/draw/components/drawToolbar/components/tools/ocrTool/components/modalTranslator.tsx
- src/app/draw/components/selectLayer/index.tsx
- src/app/draw/components/statusBar/index.tsx
- src/app/draw/page.tsx
- src/app/draw/types.ts
- src/app/menuLayout.tsx
- src/app/page.tsx
- src/app/trayIcon.tsx
- src/components/eventListener/index.tsx
- src/functions/tools.ts
- src/messages/en.ts
- src/messages/zhHans/draw.ts
- src/messages/zhHans/home.ts
- src/messages/zhHant.ts
> feats: 丰富托盘菜单

- src/app/draw/components/colorPicker/index.tsx
- src/app/draw/components/drawToolbar/components/tools/scrollScreenshotTool/index.tsx
> fix: 修复滚动截图时截取到取色器

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/core.rs
- src-tauri/src/lib.rs
- src-tauri/src/scroll_screenshot.rs
> feats: 支持单实例模式（只允许存在一个主窗口）

- src/app/draw/components/drawCacheLayer/index.tsx
- src/app/draw/components/drawToolbar/index.tsx
- src/app/draw/page.tsx
- src/app/extra.tsx
- src/app/fixedContent/components/fixedContentCore/index.tsx
- src/app/page.tsx
- src/components/keyButton/index.tsx
- src/messages/zhHans/settings.ts
- src/utils/zIndex.ts
1. 修复固定到屏幕快捷键和截图快捷键冲突
2. 优化工具栏显示
3. 支持录入 PrintScreen（但无法单独注册 PrintScreen 作为快捷键）
> fix: 修复固定到屏幕快捷键和截图快捷键冲突、优化工具栏显示和支持录入 PrintScreen

- src-tauri/src/ocr.rs
- src/app/contextWrap.tsx
- src/app/draw/components/drawToolbar/components/tools/ocrTool/components/modalTranslator.tsx
- src/app/draw/components/drawToolbar/components/tools/ocrTool/index.tsx
- src/app/draw/components/ocrBlocks/index.tsx
- src/app/fixedContent/components/ocrResult/index.tsx
- src/messages/zhHans/draw.ts
> fix: 提高 OCR 效果和 OCR 翻译默认不保留格式

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src/app/draw/components/colorPicker/index.tsx
- src/app/draw/components/drawToolbar/index.tsx
- src/app/draw/components/selectLayer/index.tsx
- src/app/draw/page.tsx
> fix: 修复工具栏不显示问题和提高 OCR 效果

- src/app/draw/components/baseLayer/index.tsx
- src/app/draw/page.tsx
> fix: 适配系统字体缩放

- src/app/fixedContent/components/fixedContentCore/index.tsx
> fix: 修复固定到屏幕的缩略功能异常

- src-tauri/src/ocr.rs
- src-tauri/src/scroll_screenshot.rs
- src-tauri/src/services/scroll_screenshot_service.rs
- src/app/draw/components/drawToolbar/components/tools/scrollScreenshotTool/index.tsx
- src/app/fixedContent/components/ocrResult/index.tsx
- src/commands/ocr.ts
- src/commands/scrollScreenshot.ts
- src/messages/zhHans/draw.ts
> fix: 优化滚动截图和提高部分场景下的 OCR 识别速度

- package.json
- pnpm-lock.yaml
- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/capabilities/default.json
- src-tauri/src/core.rs
- src-tauri/src/lib.rs
- src-tauri/src/os/mod.rs
- src-tauri/src/os/notification/windows.rs
- src-tauri/tauri.conf.json
- src/app/about/page.tsx
- src/app/draw/components/drawToolbar/index.tsx
- src/app/menuLayout.tsx
- src/commands/core.ts
- src/components/checkVersion/index.tsx
- src/messages/zhHans/about.ts
- src/messages/zhHans/common.ts
- src/services/tools/index.ts
> feats: 新版本系统通知

- src-tauri/src/file.rs
- src-tauri/src/lib.rs
- src-tauri/src/services/video_record_service.rs
- src-tauri/src/video_record.rs
- src/app/draw/components/drawToolbar/components/tools/scrollScreenshotTool/index.tsx
- src/app/draw/page.tsx
- src/app/menuLayout.tsx
- src/app/settings/functionSettings/page.tsx
- src/app/videoRecord/extra.ts
- src/app/videoRecord/toolbar/page.tsx
- src/commands/file.ts
- src/commands/videoRecord.ts
- src/components/initService/index.tsx
- src/utils/file.ts
1. 修复无法录制视频
2. 修复路径不存在导致快速保存失败的问题
> fix: 修复视频录制失败

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/capabilities/file.json
- src-tauri/src/core.rs
- src-tauri/src/services/video_record_service.rs
- src-tauri/src/video_record.rs
- src-tauri/tauri.conf.json
- src/app/draw/components/drawToolbar/components/tools/scrollScreenshotTool/index.tsx
- src/app/videoRecord/page.tsx
- src/app/videoRecord/toolbar/page.tsx
- src/commands/videoRecord.ts
- src/components/checkVersion/index.tsx
- src/components/icons/index.tsx
- src/messages/zhHans/videoRecord.ts
1. 修复关闭自动更新未立即生效
2. 修复滚动截图后按钮失效
3. 优化滚动截图
4. 版本更新通知只通知一次
5. 优化视频录制功能
> fix: 各类问题修复

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/os/ui_automation/windows.rs
- src/app/draw/components/drawToolbar/index.tsx
1. 更好的截图自动框选（Firefox 一直读不到元素，不清楚为什么……）
2. 滚动截图无法操作工具栏修复
> fix: 更好的自动框选和滚动截图无法操作工具栏修复

- src/app/contextWrap.tsx
- src/app/fixedContent/components/fixedContentCore/index.tsx
1. 固定到屏幕窗口缩放默认随鼠标位置缩放
2. 固定到屏幕的缩略模式只随鼠标位置进行缩放
3. 修复固定到屏幕缩略模式无法拖动
> feats: 固定到屏幕窗口缩放默认随鼠标位置缩放、固定到屏幕的缩略模式只随鼠标位置进行缩放、修复固定到屏幕缩略模式无法拖动

- src-tauri/tauri.conf.json
- src/app/contextWrap.tsx
- src/app/fixedContent/components/fixedContentCore/index.tsx
- src/app/settings/functionSettings/page.tsx
- src/app/settings/generalSettings/page.tsx
- src/messages/zhHans/settings.ts
> refactor: 调整固定到屏幕的设置分类

- src/app/fixedContent/components/fixedContentCore/index.tsx
> fix: 修复固定到屏幕中的链接内容跳转异常

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/core.rs
- src-tauri/src/lib.rs
- src-tauri/src/services/free_drag_window_service.rs
- src-tauri/src/services/mod.rs
- src/app/contextWrap.tsx
- src/app/draw/components/drawCacheLayer/index.tsx
- src/app/draw/components/drawToolbar/index.tsx
- src/app/draw/components/statusBar/index.tsx
- src/app/fixedContent/components/fixedContentCore/index.tsx
- src/app/settings/generalSettings/page.tsx
- src/commands/core.ts
- src/messages/zhHans/settings.ts
1. 修复部分情况无法拖动窗口
2. 修复未完成文字编辑后再次唤起截图工具栏显示错误
3. 可设置截图快捷键提示透明度
> fix: 修复部分情况无法拖动窗口、修复未完成文字编辑后再次唤起截图工具栏显示错误、可设置截图快捷键提示透明度

- src/app/contextWrap.tsx
- src/app/page.tsx
- src/components/translator/index.tsx
> feat: 翻译功能新增清空、复制按钮；优化配置加载速度

- src-tauri/src-crates/app-utils/src/lib.rs
- src-tauri/src-crates/tauri-commands/core/src/lib.rs
- src/app/draw/actions.ts
- src/app/draw/components/drawToolbar/components/tools/extraTool/index.tsx
- src/app/draw/extra.ts
- src/app/draw/page.tsx
- src/app/fixedContent/page.tsx
- src/app/fullScreenDraw/switchMouseThrough/page.tsx
- src/app/videoRecord/page.tsx
- src/app/videoRecord/toolbar/page.tsx
- src/commands/core.ts
- src/messages/zhHans/draw.ts
- src/utils/window.ts
> fix: 修复窗口定位问题

- src-tauri/src-crates/app-utils/src/lib.rs
> fix: 统一截图格式为 RGBA

- src-tauri/tauri.conf.json
- src/app/fullScreenDraw/components/drawCore/components/serialNumberTool/index.tsx
> fix: 序列号文字居中

- src-tauri/src-crates/app-os/src/ui_automation/windows.rs
- src-tauri/tauri.conf.json
- src/app/contextWrap.tsx
- src/app/draw/components/drawToolbar/components/keyEventWrap/extra.ts
- src/app/draw/components/drawToolbar/components/tools/ocrTool/index.tsx
- src/app/draw/components/drawToolbar/index.tsx
- src/app/draw/components/ocrBlocks/index.tsx
- src/app/draw/components/statusBar/index.tsx
- src/app/draw/page.tsx
- src/app/extra.tsx
- src/app/fullScreenDraw/components/drawCore/extra.tsx
- src/app/page.tsx
- src/app/settings/generalSettings/page.tsx
- src/app/trayIcon.tsx
- src/functions/screenshot.ts
- src/messages/zhHans/draw.ts
- src/messages/zhHans/settings.ts
1. 支持 OCR 自动翻译
2. 修复 Windows 下截图固定到屏幕窗口时异常聚焦
3. 修复截图窗口多显示器的弹窗定位问题
> feats: 支持 OCR 自动翻译

- src/app/draw/actions.ts
- src/app/draw/page.module.css
- src/app/draw/page.tsx
- src/app/fixedContent/components/fixedContentCore/index.tsx
> fix: 修复显示模糊问题

- src/app/contextWrap.tsx
- src/app/draw/components/selectLayer/index.tsx
- src/app/draw/components/statusBar/index.tsx
- src/app/fixedContent/components/fixedContentCore/index.tsx
- src/app/fullScreenDraw/switchMouseThrough/page.tsx
- src/app/trayIcon.tsx
- src/app/videoRecord/page.tsx
- src/app/videoRecord/toolbar/page.tsx
- src/commands/core.ts
- src/components/eventListener/index.tsx
- src/hooks/useTextScaleFactor.tsx
1. 禁用选取窗口元素增强
2. 优化选取窗口/选取窗口子元素的切换逻辑
3. 优化托盘菜单
4. 修复固定到屏幕内容偏移、模糊问题
5. 修复视频录制工具栏定位问题
6. 禁止视频录制时通过截图更改录制区域
7. 修复全屏画布定位问题
> fix: 修复各类问题

- src-tauri/src-crates/app-services/src/video_record_service.rs
- src-tauri/src/video_record.rs
- src/app/contextWrap.tsx
- src/app/settings/functionSettings/page.tsx
- src/app/videoRecord/toolbar/page.tsx
- src/commands/videoRecord.ts
- src/components/eventListener/index.tsx
- src/messages/zhHans/settings.ts
> feats: 视频录制清晰度默认 1080p，增加清晰度设置

- src-tauri/src-crates/app-services/src/video_record_service.rs
- src-tauri/src-crates/tauri-commands/core/src/lib.rs
1. 修复 macOS 下的视频录制问题
2. 修复编译告警
> fix: 修复 macOS 下的视频录制问题

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/lib.rs
- src/app/contextWrap.tsx
- src/app/draw/components/baseLayer/index.tsx
- src/app/draw/components/captureHistory/index.tsx
- src/app/draw/components/drawToolbar/components/tools/scrollScreenshotTool/index.tsx
- src/app/draw/page.tsx
- src/app/fixedContent/components/fixedContentCore/index.tsx
- src/app/settings/functionSettings/components/testChat.tsx
- src/app/settings/generalSettings/page.tsx
- src/app/settings/systemSettings/page.tsx
- src/app/tools/chat/page.tsx
- src/app/trayIcon.tsx
- src/app/videoRecord/toolbar/page.tsx
- src/commands/scrollScreenshot.ts
- src/components/checkVersion/index.tsx
- src/components/eventListener/index.tsx
- src/components/keyButton/index.tsx
- src/messages/zhHans/settings.ts
- src/services/tools/index.ts
- src/utils/appStore.ts
- src/utils/audio.ts
- src/utils/captureHistory.ts
- src/utils/clipboard.ts
- src/utils/log.ts
> fix: 修复应用崩溃

- src/app/fixedContent/components/ocrResult/index.tsx
> fix: 修复 OCR 重复执行问题

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src-crates/app-services/src/ocr_service.rs
- src-tauri/src/core.rs
- src-tauri/src/lib.rs
- src-tauri/src/main.rs
- src-tauri/tauri.conf.json
- src/app/draw/components/baseLayer/index.tsx
- src/app/draw/components/colorPicker/actions.ts
- src/app/draw/components/colorPicker/index.tsx
- src/app/draw/components/colorPicker/renderActions.ts
- src/app/draw/components/colorPicker/workers/getPixels.ts
- src/app/draw/components/colorPicker/workers/renderWorker.ts
- src/app/draw/page.tsx
- src/app/draw/types.ts
- src/app/fixedContent/components/ocrResult/index.tsx
- src/components/eventListener/index.tsx
- src/functions/ocr.ts
> perf: 内存优化

- src-tauri/tauri.conf.json
- src/app/draw/actions.ts
- src/app/draw/page.tsx
- src/app/draw/types.ts
> fix: 修复开启复制后自动保存截图标记失效

- src-tauri/Cargo.toml
- src-tauri/src-crates/app-os/src/ui_automation/windows.rs
- src/app/menuLayout.tsx
- src/app/page.tsx
- src/components/globalShortcut/index.tsx
> fix: 全局快捷键注册修复

- src-tauri/.gitignore
- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src/main.rs
- src-tauri/tauri.conf.json
> chore: 更新用户配置

- src-tauri/src-crates/tauri-commands/core/src/lib.rs
- src-tauri/src/core.rs
- src-tauri/src/lib.rs
- src-tauri/tauri.conf.json
- src/app/page.tsx
- src/commands/index.ts
> fix: 自启动不显示窗口

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/tauri.conf.json
> chore: 更新项目名

- src-tauri/src/lib.rs
- src-tauri/src/main.rs
> fix: 日志文件使用用户系统时区

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src-crates/app-services/Cargo.toml
- src-tauri/src-crates/app-services/src/file_cache_service.rs
- src-tauri/src-crates/app-services/src/lib.rs
- src-tauri/src-crates/tauri-commands/file/src/lib.rs
- src-tauri/src/file.rs
- src-tauri/src/lib.rs
- src-tauri/tauri.conf.json
- src/app/contextWrap.tsx
- src/app/draw/page.tsx
- src/app/fixedContent/components/fixedContentCore/index.tsx
- src/commands/file.ts
- src/functions/screenshot.ts
- src/utils/captureHistory.ts
- src/utils/index.ts
> perf: 优化配置文件加载速度

- src/app/draw/components/drawToolbar/components/keyEventWrap/index.tsx
- src/app/fixedContent/components/fixedContentCore/index.tsx
- src/app/fixedContent/components/ocrResult/index.tsx
- src/app/fullScreenDraw/components/drawCore/components/excalidrawKeyEventHandler.tsx
- src/app/fullScreenDraw/components/drawCore/components/serialNumberTool/index.tsx
- src/app/fullScreenDraw/components/drawCore/excalidrawRenders/layerButtonRender.tsx
> fix: 修复快速切换缩略模式时窗口无法恢复

- src/app/fixedContent/components/fixedContentCore/components/drawLayer/index.tsx
- src/app/fixedContent/components/fixedContentCore/components/drawLayer/toolbar.tsx
- src/app/fixedContent/components/fixedContentCore/index.tsx
- src/core/hotKeys/index.tsx
> fix: 修复部分热键无效的问题

- src-tauri/tauri.conf.json
- src/app/fixedContent/components/fixedContentCore/components/drawLayer/index.tsx
- src/app/fixedContent/components/fixedContentCore/index.tsx
- src/app/fixedContent/components/ocrResult/index.tsx
- src/hooks/useTextScaleFactor.tsx
- src/utils/zIndex.ts
> fix: 修复圆角截图固定到屏幕后无圆角边框

- src/app/draw/actions.ts
> fix: 修复阴影截图未隐藏绘制内容

- src/app/draw/components/selectLayer/components/resizeToolbar/components/resizeModal.tsx
> fix: 修复截图调整大小表单重置值的问题

- src-tauri/src/lib.rs
> fix: 修复通过任务栏关闭主窗口无法唤出截图等功能

- src/app/fixedContent/components/fixedContentCore/components/drawLayer/index.tsx
- src/app/fixedContent/components/fixedContentCore/components/drawLayer/toolbar.tsx
- src/app/fixedContent/components/fixedContentCore/index.tsx
- src/app/fullScreenDraw/components/drawCore/extra.tsx
> feat: 绘制模式添加确认按钮

- src/app/fixedContent/components/fixedContentCore/components/drawLayer/toolbar.tsx
- src/messages/zhHans/draw.ts
> fix: 绘制模式确认按钮添加提示

- src/app/draw/actions.ts
- src/app/draw/components/drawCacheLayer/extra.tsx
- src/app/draw/components/drawCacheLayer/index.tsx
- src/app/draw/components/drawToolbar/index.tsx
- src/app/draw/page.tsx
- src/app/fixedContent/components/fixedContentCore/components/drawLayer/index.tsx
- src/app/fullScreenDraw/components/drawCore/extra.tsx
- src/app/fullScreenDraw/components/drawCore/index.tsx
- src/app/fullScreenDraw/page.tsx
- src/utils/appStore.ts
> fix: 修复绘图样式保存问题

- src/app/draw/components/drawCacheLayer/index.tsx
- src/app/draw/components/selectLayer/components/resizeToolbar/index.tsx
- src/app/fullScreenDraw/components/drawCore/components/serialNumberTool/index.tsx
- src/app/fullScreenDraw/components/drawCore/excalidrawRenders/index.tsx
- src/app/fullScreenDraw/components/drawCore/excalidrawRenders/layoutMenuRender.tsx
- src/app/fullScreenDraw/components/drawCore/excalidrawRenders/serialNumberEditor.tsx
- src/app/fullScreenDraw/components/drawCore/index.tsx
- src/messages/zhHans/draw.ts
> feat: 快速编辑序列号

- src/app/draw/page.tsx
- src/app/fullScreenDraw/components/drawCore/components/serialNumberTool/index.tsx
> fix: 修复序列号使用箭头时自增序号异常

- src-tauri/src-crates/app-os/src/ui_automation/windows.rs
> fix: 修复自动框选部分情况下初始化异常

- src/app/draw/components/statusBar/index.tsx
- src/app/draw/page.tsx
- src/app/fixedContent/components/fixedContentCore/index.tsx
- src/messages/zhHans/draw.ts
> feat: 固定到屏幕支持旋转、修复刘海屏遮挡提示

- src/app/contextWrap.tsx
- src/app/draw/components/colorPicker/index.tsx
- src/app/fixedContent/components/fixedContentCore/index.tsx
- src/app/settings/functionSettings/page.tsx
- src/messages/zhHans/settings.ts
> feat: 支持固定到屏幕后自动复制

- src-tauri/src-crates/app-services/src/video_record_service.rs
- src-tauri/src/video_record.rs
- src/app/contextWrap.tsx
- src/app/settings/functionSettings/page.tsx
- src/app/videoRecord/toolbar/page.tsx
- src/commands/videoRecord.ts
- src/messages/zhHans/settings.ts
> feat: 视频录制支持 APNG

- src/app/draw/components/selectLayer/extra.ts
- src/app/draw/components/selectLayer/index.tsx
- src/messages/zhHans/draw.ts
> fix: 修复拖动选区不支持保持宽高一直

- src/app/draw/components/ocrBlocks/index.tsx
- src/app/fixedContent/components/fixedContentCore/index.tsx
- src/app/fixedContent/components/ocrResult/index.tsx
- src/app/trayIcon.tsx
> fix: 修复右键菜单潜在的问题

- src/app/draw/components/drawToolbar/components/tools/extraTool/index.tsx
- src/app/draw/components/drawToolbar/index.tsx
- src/app/draw/components/selectLayer/extra.ts
- src/app/draw/components/selectLayer/index.tsx
> fix: 修复扫描二维码无法复制的问题

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src-crates/app-services/Cargo.toml
- src-tauri/src-crates/app-services/src/file_cache_service.rs
- src-tauri/src/file.rs
- src/app/settings/systemSettings/page.tsx
- src/commands/file.ts
- src/messages/zhHans/settings.ts
> fix: 支持自定义数据目录

- src/app/settings/systemSettings/page.tsx
- src/utils/captureHistory.ts
> fix: 修复 lint 警告

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src-crates/app-utils/Cargo.toml
- src-tauri/src-crates/app-utils/src/lib.rs
- src-tauri/src-crates/app-utils/src/monitor_info.rs
- src-tauri/src-crates/tauri-commands/screenshot/src/lib.rs
- src-tauri/src-crates/tauri-commands/scroll-screenshot/src/lib.rs
> fix: Windows 下应用放大镜反色效果时取消反色

- src/app/contextWrap.tsx
- src/app/draw/actions.ts
- src/app/draw/page.tsx
- src/app/settings/systemSettings/page.tsx
- src/messages/zhHans/settings.ts
> perf: 更快的截图复制

- src/app/draw/actions.ts
> fix: 修复编译问题

- src/app/draw/page.tsx
- src/app/fullScreenDraw/components/drawCore/components/serialNumberTool/index.tsx
> fix: 修复序列号无法编辑

- src-tauri/Cargo.toml
- src-tauri/src-crates/app-services/src/file_cache_service.rs
- src-tauri/src/lib.rs
- src/app/contextWrap.tsx
- src/app/settings/functionSettings/page.tsx
> fix: 修复 CPU 占用过高的问题

- src/app/fullScreenDraw/components/drawCore/index.tsx
> fix: 修复部分绘制属性不保存的问题

- src/app/contextWrap.tsx
- src/app/draw/page.tsx
- src/app/extra.tsx
- src/app/trayIcon.tsx
- src/components/globalShortcut/components/changeDelaySeconds.tsx
- src/components/globalShortcut/index.tsx
- src/functions/screenshot.ts
- src/messages/zhHans/home.ts
> feat: 延迟截图

- src/app/draw/components/statusBar/index.tsx
> fix: 修复 OCR 复制可能复制到提示文本

- src-tauri/src-crates/app-utils/src/lib.rs
- src-tauri/src-crates/tauri-commands/core/src/lib.rs
- src-tauri/src-crates/tauri-commands/screenshot/src/lib.rs
- src-tauri/src/core.rs
- src-tauri/src/screenshot.rs
- src/app/contextWrap.tsx
- src/app/draw/page.tsx
- src/app/settings/systemSettings/page.tsx
- src/app/videoRecord/toolbar/page.tsx
- src/commands/core.ts
- src/commands/screenshot.ts
- src/messages/zhHans/settings.ts
> feat: 支持关闭多显示器截图

- package.json
- pnpm-lock.yaml
- src/app/contextWrap.tsx
- src/app/draw/components/selectLayer/components/resizeToolbar/components/resizeModal.tsx
- src/app/fullScreenDraw/components/drawCore/excalidrawRenders/colorPickerPopoverRender.tsx
- src/app/fullScreenDraw/components/drawCore/excalidrawRenders/index.tsx
- src/app/fullScreenDraw/components/drawCore/excalidrawRenders/layoutMenuRender.tsx
- src/app/fullScreenDraw/components/drawCore/excalidrawRenders/radioSelection.tsx
- src/app/fullScreenDraw/components/drawCore/excalidrawRenders/radioSlider.tsx
- src/app/fullScreenDraw/components/drawCore/excalidrawRenders/rangeRender.tsx
- src/app/fullScreenDraw/components/drawCore/index.tsx
- src/app/settings/functionSettings/page.tsx
- src/app/settings/generalSettings/page.tsx
- src/app/settings/hotKeySettings/page.tsx
- src/app/settings/systemSettings/page.tsx
- src/app/tools/chat/components/updateOrCreateWorkflow/index.tsx
- src/components/translator/index.tsx
- src/messages/zhHans/settings.ts
> feat: 支持启用更精细的大小控制

- src/app/contextWrap.tsx
- src/app/draw/components/drawToolbar/index.tsx
- src/app/fixedContent/components/fixedContentCore/components/drawLayer/toolbar.tsx
- src/app/fullScreenDraw/components/drawCore/components/serialNumberTool/index.tsx
- src/app/fullScreenDraw/components/drawCore/index.tsx
- src/app/fullScreenDraw/components/toolbar/index.tsx
- src/app/settings/functionSettings/page.tsx
- src/app/settings/generalSettings/page.tsx
- src/messages/zhHans/settings.ts
- src/utils/appStore.ts
> feat: 支持配置独立的工具样式

- src/app/draw/components/selectLayer/index.tsx
> fix: 修复选区渲染错误

- src/app/draw/components/drawToolbar/components/tools/scanQrcodeTool.tsx
- src/app/draw/components/drawToolbar/index.tsx
- src/app/draw/components/ocrBlocks/index.tsx
- src/app/draw/page.tsx
- src/app/fixedContent/components/fixedContentCore/index.tsx
- src/app/fixedContent/components/ocrResult/index.tsx
- src/app/fullScreenDraw/components/drawCore/excalidrawRenders/SubToolEditor.tsx
- src/app/fullScreenDraw/components/drawCore/index.tsx
- src/app/settings/functionSettings/page.tsx
- src/hooks/useTextScaleFactor.tsx
- src/utils/clipboard.ts
> fix: 修复 OCR 划选到意外的文本

- src/app/draw/components/captureHistory/index.tsx
- src/app/draw/components/selectLayer/index.tsx
- src/utils/captureHistory.ts
> fix: 修复截图历史的一些问题

- src/app/contextWrap.tsx
- src/app/draw/components/drawToolbar/components/tools/drawExtraTool/index.tsx
- src/app/draw/components/drawToolbar/index.tsx
- src/app/settings/generalSettings/page.tsx
- src/messages/zhHans/settings.ts
> feat: 支持隐藏水印工具

- src/app/draw/page.tsx
- src/app/fixedContent/components/ocrResult/index.tsx
- src/utils/clipboard.ts
> fix: 修复复制文本问题

- src/app/fixedContent/components/ocrResult/index.tsx
> fix: 修复 OCR 结果的显示效果

- src/app/fullScreenDraw/components/drawCore/index.tsx
> fix: 修复工具切换的问题

- src/app/draw/components/colorPicker/extra.tsx
- src/app/draw/components/drawCacheLayer/index.tsx
- src/app/draw/components/drawToolbar/components/dragButton/extra.ts
- src/app/draw/components/drawToolbar/components/dragButton/index.tsx
- src/app/draw/components/drawToolbar/components/subTools.tsx
- src/app/draw/components/selectLayer/components/resizeToolbar/index.tsx
- src/app/draw/extra.ts
- src/app/draw/page.tsx
- src/app/fixedContent/components/ocrResult/index.tsx
- src/app/fullScreenDraw/components/drawCore/excalidrawRenders/layoutMenuRender.tsx
- src/app/fullScreenDraw/components/drawCore/excalidrawRenders/radioSelection.tsx
- src/app/fullScreenDraw/components/drawCore/extra.tsx
> fix: 优化工具栏定位

- src/app/fixedContent/components/fixedContentCore/index.tsx
> fix: 修复固定到屏幕拖动时会选中图片

- src-tauri/Cargo.lock
- src/app/draw/components/drawToolbar/components/dragButton/index.tsx
- src/app/draw/components/drawToolbar/components/subTools.tsx
- src/app/fullScreenDraw/components/drawCore/excalidrawRenders/layoutMenuRender.tsx
> fix: 修复工具栏初始定位问题

- src-tauri/Cargo.lock
- src/app/fixedContent/components/ocrResult/index.tsx
> fix: 修复 OCR 结果为空的一些问题

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/src-crates/tauri-commands/core/Cargo.toml
- src-tauri/src-crates/tauri-commands/core/src/lib.rs
- src-tauri/src/core.rs
- src-tauri/src/lib.rs
- src/commands/core.ts
- src/utils/captureHistory.ts
> fix: 修复截图历史可能因数据丢失而不删除过期文件

- src/app/draw/components/selectLayer/index.tsx
> perf: 优化渲染性能

- src/app/draw/components/baseLayer/actions.ts
- src/app/draw/components/colorPicker/actions.ts
> fix: 修复编译错误

- src/utils/file.ts
> fix: 修复更改视频等目录后默认输出目录错误

- src-tauri/src-crates/app-utils/src/monitor_info.rs
- src/app/contextWrap.tsx
- src/app/draw/components/drawToolbar/index.tsx
- src/app/draw/page.tsx
- src/components/initService/index.tsx
- src/utils/log.ts
1. 修复 Iter.reduce 在较低版本浏览器不兼容的问题
> fix: 修复 Iter.reduce 在较低版本浏览器不兼容的问题

- eslint.config.mjs
- package.json
- pnpm-lock.yaml
- src/app/draw/components/drawToolbar/components/tools/blurTool.tsx
- src/app/draw/components/drawToolbar/index.tsx
- src/utils/clipboard.ts
- tsconfig.json
> fix: 降低 JS 的 API 等级提高兼容性检查

- src/app/fullScreenDraw/components/drawCore/index.tsx
> fix: 使用滚轮更改线条粗细等不再循环

- package.json
- pnpm-lock.yaml
- src-tauri/src-crates/app-utils/src/lib.rs
- src-tauri/src-crates/app-utils/src/monitor_info.rs
> fix: 修复 macOS 下多显示器截图错误

- src/app/fullScreenDraw/components/drawCore/excalidrawRenders/serialNumberEditor.tsx
> fix: 选择工具下支持更改序列号数字

- src-tauri/src/core.rs
- src-tauri/src/lib.rs
- src/app/contextWrap.tsx
- src/app/draw/components/drawToolbar/components/subTools.tsx
- src/app/settings/systemSettings/page.tsx
- src/commands/core.ts
- src/components/initService/index.tsx
- src/messages/zhHans/settings.ts
- src/utils/index.ts
> feat: 优化应用的管理员权限和开机自启设置

- src-tauri/src/core.rs
- src-tauri/src/lib.rs
- src/app/contextWrap.tsx
- src/app/settings/systemSettings/page.tsx
- src/commands/core.ts
- src/components/initService/index.tsx
- src/messages/zhHans/settings.ts
> feat: 支持开关日志输出

- package.json
- pnpm-lock.yaml
- src/app/contextWrap.tsx
- src/app/draw/components/baseLayer/actions.ts
- src/app/draw/components/baseLayer/baseLayerRenderActions.ts
- src/app/draw/components/baseLayer/index.tsx
- src/app/draw/components/baseLayer/workers/renderWorker.ts
- src/app/draw/components/baseLayer/workers/renderWorkerTypes.ts
- src/app/draw/components/drawToolbar/components/tools/blurTool.tsx
- src/app/draw/components/drawToolbar/index.tsx
- src/app/fullScreenDraw/components/drawCore/excalidrawRenders/SubToolEditor.tsx
- src/app/fullScreenDraw/components/drawCore/extra.tsx
> feat: 模糊画笔

- src/app/draw/components/selectLayer/index.tsx
- src/messages/zhHans/settings.ts
> fix: 自动框选切换层级反转 Y 轴以符合操作直觉

- src/app/fullScreenDraw/components/drawCore/excalidrawRenders/SubToolEditor.tsx
- src/app/fullScreenDraw/components/drawCore/excalidrawRenders/radioSelection.tsx
> fix: 修复多显示器下滤镜选择组件显示问题

- src/app/tools/captureHistory/page.tsx
> fix: 修复截图历史日期筛选问题

- src/app/settings/functionSettings/page.tsx
- src/app/settings/generalSettings/page.tsx
> fix: 修复选择组件鼠标悬浮提示显示错误

- src/app/draw/components/baseLayer/actions.ts
- src/app/draw/components/baseLayer/baseLayerRenderActions.ts
- src/app/draw/components/baseLayer/index.tsx
- src/app/draw/components/baseLayer/workers/renderWorker.ts
- src/app/draw/components/baseLayer/workers/renderWorkerTypes.ts
- src/app/draw/components/captureHistory/index.tsx
- src/app/draw/components/drawLayer/index.tsx
- src/app/draw/components/drawToolbar/components/tools/blurTool.tsx
- src/app/draw/components/drawToolbar/components/tools/drawExtraTool/components/watermarkTool.tsx
- src/app/draw/components/drawToolbar/components/tools/highlightTool.tsx
- src/app/draw/components/drawToolbar/index.tsx
- src/app/draw/components/selectLayer/index.tsx
- src/app/draw/extra.ts
> fix: 修复高亮的一些问题

- src/app/draw/components/drawToolbar/components/keyEventWrap/index.tsx
- src/app/trayIcon.tsx
> feat: 截取全屏添加到托盘菜单

- src/app/tools/captureHistory/page.tsx
- src/components/globalShortcut/index.tsx
> fix: 修复全局快捷键无法注册的问题
